### ISSUE TITLE
indicate if a dropMembership is pending approval

### ISSUE THREAD

**Issue by MercenaryJosh** [azurestandard/api-spec#115]
The dropMembership model needs to indicate if it is still awaiting approval from customer service. This is part of the [spec](https://docs.google.com/document/d/1dwayyitTQT5ma-UhFfkC16i6aVrJ2ArV-HnUdWyst10/edit#heading=h.4lzssgbotfpz):

> A status of pending needs to be placed on the customer’s drop membership association with the ability for a customer service representative to change that flag to approved. When this feature gets added into beehive we can set all existing drop members as approved (pending false) to start with. Any new member added to a drop is set as approved except if they come from the website as described here on a semi-open drop. Prospective members can retrieve information on a drop’s location, drop id and future stops, and they can place orders on those stops. Otherwise, prospective members should have the same access to drop data as non-members. The idea is that in most cases, customer-service will be able to get prospective members approved as full members by cutoff time, so we don’t want to hold-up order placement. But we also don’t want to leak private information to un-approved customers.

This can be done by either adding a 'pending' boolean property or possibly a 'status' enum string property if there is the potential for other status (besides 'pending' and 'active') to be used in the future.

**Comment by wking** [comment]
On Mon, May 09, 2016 at 12:14:44PM -0700, MercenaryJosh wrote:
> This can be done by either adding a 'pending' boolean property or
> possibly a 'status' enum string property if there is the potential
> for other status (besides 'pending' and 'active') to be used in the
> future.

Both of these approaches sound fine to me.  At least, I can't think of
another status in the member-accepting workflow besides "pending" and
"accepted".  I'd recommend pending/status be required (for all
methods), because the sane default would depend on whether the target
drop was open or not.  And baking that drop.exclusivity dependency
into the pending/status docs doesn't seem like it would be worth the
trouble.
