### ISSUE TITLE
Get Swagger UI working

### ISSUE THREAD

**Issue by igregson** [azurestandard/api-spec#165]
As I understand it, pasting the spec's JSON url into the URL input [here](http://petstore.swagger.io/#/) should work. When attempting, I get this: 

![2016-10-17_09-51-37](https://cloud.githubusercontent.com/assets/2054975/19446805/5a9e03c4-944f-11e6-95f6-78180e7586aa.png)

**Comment by wking** [comment]
On Mon, Oct 17, 2016 at 09:54:38AM -0700, Isaac Gregson wrote:
> As I understand it, pasting the spec's JSON url into the URL input
> [here](http://petstore.swagger.io/#/) should work. When attempting,
> I get this:
>
>   Can't read from server. It may not have the appropriate
>   access-control-origin settings.

GitHub doesn't put CORS headers on their own content.  In the past
we've had success with [1], but that currently gives me the same
error.  The rawgit URL [2] is setting:

  access-control-allow-origin: *

so I'm not sure why we're seeing this CORS issue with it (maybe that
it's missing an Access-Control-Expose-Headers header?).

Putting our JSON up somewhere with proper CORS should help, although
it's been a while since I tried rendering the JSON; there may be some
bits in our JSON that the Swagger engine doesn't like ;).

[1]: http://petstore.swagger.io/?url=https%3A%2F%2Frawgit.com%2Fazurestandard%2Fapi-spec%2Fmaster%2Fpublic.json
[2]: https://rawgit.com/azurestandard/api-spec/master/public.json

**Comment by igregson** [comment]
This now works.
