### ISSUE TITLE
move resend to /emails/{id}/resend

### ISSUE THREAD

**Issue by igregson** [azurestandard/api-spec#168]
@wking

Related to multiple email support ([website issue 624](https://github.com/azurestandard/website/issues/624)):

**Resending the confirmation email:**

With the current api spec, there seem to be two ways to achieve this:

1. POST to `/emails/resend` - which requires a token that is only returned after initially creating the email (and is thus not possible to get again after page refresh, unless we stored it in localstorage or something, which at that point seems to overly complicate the task).
2. PUT to `/email/{id}` - which requires the user's password (arguably bad UX for such a simple task as having a confirmation email resent).

Since a POST request to `/emails/resend` seems specifically intended for this task it appears the recommended approach. However, a PUT request to `/email/{id}` is much easier since it does not require a token. Perhaps there may be a way to drop the token requirement for `/emails/resend` or otherwise PUT to ``/email/{id}` without a password? Anything I'm missing here?

Also, I don't see why a PUT to `/email/{id}/resend` with the email's ID wouldn't work (since the ID is returned on POST (creation) of the email via `/emails/create` and on the loading of emails (via GET to `/emails`), so it's accessible in all cases the front-end would need it for making a PUT to `/emails/{id}/resend`). Reading over the initial implementation of the API it seems this was the approach... I've read the [PR notes here](https://github.com/azurestandard/api-spec/pull/149#issue-172022037) but since there's access to the ID I'm not sure on why this approach wouldn't work.

**Comment by wking** [comment]
On Fri, Oct 28, 2016 at 02:41:10AM -0700, Isaac Gregson wrote:
> 1. POST to `/emails/resend` - which requires a token that is only
>    returned after initially creating the email (and is thus not
>    possible to get again after page refresh, unless we stored it in
>    localstorage or something, which at that point seems to overly
>    complicate the task).
> 2. PUT to `/email/{id}` - which requires the user's password
>    (arguably bad UX for such a simple task as having a confirmation
>    email resent).

In most cases, the user will be using a cookie which is preserved
across refreshes.  So you can ‘PUT /email/{id}’ (with data fetched
from ‘GET /email/{id}’) to get a new token if you lose your original.

> Since a POST request to `/emails/resend` seems specifically intended
> for this task it appears the recommended approach. However, a PUT
> request to `/email/{id}` is much easier since it does not require a
> token.

A PUT has the potential for unwanted side effects (e.g. you might
clobber change another user made to that email in parallel).  POSTing
to /emails/resend, on the other hand, has not such risk.  We could add
/emails/{id}/resend and accept the non-token cookie/basic credentials
there.  If you just refreshed (and lost your resend token), you
wouldn't know there's a confirmation in progress.  But if all you want
to do is clear an error, you could skip ‘PUT /emails/{id}’ entirely
and just ‘POST /emails/{id}/resend’.

> Perhaps there may be a way to drop the token requirement for
> `/emails/resend` or otherwise PUT to ``/email/{id}` without a
> password? Anything I'm missing here?

Without a token (for POST /emails/resend) or credentials (for PUT
/email/{id}), malicious users could use our API to pester customers
with lots of email-confirmation messages.

> Also, I don't see why a PUT to `/email/{id}/resend` with the email's
> ID wouldn't work…

POSTing to /email/{id}/resend would work, since the only way to get
the resend token is by looking at the updatedEmail response.  However,
POSTing to /email/{id}/confirm would not work, for the reasons
discussed in #149.  So we need /emails/confirm, and I'd left the ID
out of /emails/resend for consistency with the sibling token-based
endpoint.  If we plan on supporting both tokens and cookie/basic
credentials for resend, we'll want to move resend to
/emails/{id}/resend.

**Comment by igregson** [comment]
> If we plan on supporting both tokens and cookie/basic
credentials for resend, we'll want to move resend to
/emails/{id}/resend.

@wking From the team call on 9/28, let's go with this approach. The end-goal for the UX is to not have to prompt the user for their password for resending the confirmation email. Removing the question label from this issue and renaming appropriately.
