### ISSUE TITLE
Add SEO Title and Description to Categories

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/api-spec#213]
In discussions with @davidcross and @davidmcatee-azure about improving our SEO standings we would like the ability to store an SEO Title and Description for a category.  This new fields would then be used by the website for our HTML Title and Meta Description tags.

These fields should be added to the `/categories` table as:

1. seo-name
2. seo-description

The following tasks will need to be completed in the following order:

1. API Spec needs to be updated - This Issue
2. Backend work - [Beehive #3030](https://github.com/azurestandard/beehive/issues/3030)
3. Internal Website for Data Entry - [Internal-Website #190](https://github.com/azurestandard/internal-website/issues/190)
4. Website will need to consume the data - [Website #1736](https://github.com/azurestandard/website/issues/1736)

**Comment by wking** [comment]
On Fri, Sep 01, 2017 at 04:07:51PM +0000, Tom Peters wrote:
> 1. seo-title

We already have name and short-name.  short-name landed in 67cd688
(when we went from name and description to name and short-name) with
notes about how short-name was going to be useful for SEO in URLs and
such.  Can you give an example of a value you'd use for a title tag
that differs from the name value?

> 2. seo-description

Is there a reason to make this SEO-specific?  I'd rather just restore
a ‘description’ field with a stand-alone category description.  In
67cd688, I'd cited Susan saying we wouldn't need a longer description,
but I think the meta description use case is grounds to overturn that
decision.

**Comment by tompetersjr** [comment]
> > 1. seo-title
> 
> We already have name and short-name.

This is not really going to be a short name as more a human readable name for SEO purposes.  I think there is a distinct enough difference that we need a separate field.   Although I not sure short name is being used.  We could repurpose it if that is the case but I also think we should rename it to seo-title for the specific use.  I do not have examples off the top of my head but we would have someone knowledgable in SEO filling this out and maintaining it.

> > 2. seo-description
> 
> I'd rather just restore a ‘description’ field with a stand-alone category description

This is exactly what we need.

**Comment by wking** [comment]
On Fri, Sep 01, 2017 at 04:26:08PM +0000, Tom Peters wrote:
> > > 1. seo-title
> > 
> > We already have name and short-name.
> 
> This is not really going to be a short name as more a human readable
> name for SEO purposes.  I think there is a distinct enough
> difference that we need a separate field.  Although I not sure short
> name is being used.  We could repurpose it if that is the case but I
> also think we should rename it to seo-title for the specific use.

From the spec [1]:

* name
  A phrase naming the category.  This should be understandable (but
  not necessarily unique) without any further context.  It must be
  unique for categories sharing a given parent.

* short-name
  A word or two naming the category.  A shortened version of the full
  name that drops any words already contained in the category's
  ancestors' short names.  This will be used in places where the
  ancestor short names are in close proximity (e.g. URL slugs) to
  avoid having the same word many times.

It sounds like ‘name’ is a good candidate for a page title.

> I do not have examples off the top of my head but we would have
> someone knowledgable in SEO filling this out and maintaining it.

+1 to having someone knowledgeable in SEO at least advising on both
name and short-name, as both of those have SEO implications.

[1]: https://github.com/azurestandard/api-spec/blob/f1d3650b0623f8dc2d503483669a1b457cb0bd61/public.json#L7923-L7930

**Comment by wking** [comment]
On Fri, Sep 01, 2017 at 09:15:02AM -0700, W. Trevor King wrote:
> On Fri, Sep 01, 2017 at 04:07:51PM +0000, Tom Peters wrote:
> > 1. seo-title
> 
> … Can you give an example of a value you'd use for a title tag that
> differs from the name value?

@davidmcatee-azure pointed out some places where the website
hard-codes these [1].

Here are some examples of places where we set short-name:

  for cat in Category.objects.exclude(short_name='').order_by('id')[:30]:
      print(u'{}\t{}\t{}'.format(cat.id, cat.short_name, cat.name))
  # 17260   Cod Liver       Cod Liver Oil
  # 17291   Fish    Fish Oils
  # 17298   Evening Primrose        Evening Primrose Oil
  # 17303   Bruess Blend    Bruess Juice Blend
  # 17310   Celery/Celeriac Celery/Celeriac Juice
  # 17311   Blueberry/Bilberry      Blueberry/Bilberry Juice
  # 17312   Carrot  Carrot Juice
  # 17313   Beet    Beet Juice
  # 17314   Sauerkraut      Sauerkraut Juice
  # 17315   Green   Green Juices
  # 17318   Elderberry      Elderberry Juice
  # 17604   Whole Food      Whole Food Supplements
  # 17695   E       Vitamin E
  # 17698   D       Vitamin D
  # 17704   A       Vitamin A
  # 17708   C       Vitamin C
  # 17717   B       Vitamin B
  # 17725   K       Vitamin K
  # 17772   Single  Single Herbs
  # 18114   Combo   Combo Herbs
  # 18179   Protein Protein Powders & Bars
  # 18180   Blends  Protein Blends
  # 18183   Hemp    Hemp Protein
  # 18184   Soy-Free        Soy-Free Protein
  # 18186   Goat Milk       Goat Milk Protein
  # 18187   Soy     Soy Protein
  # 18190   Goat Whey       Goat Whey Protein
  # 18191   Bars    Protein Bars
  # 18203   Drinks  Protein Drinks
  # 18207   Egg     Egg White Protein

And here are details for our root categories:

  for cat in Category.objects.filter(parent=None).order_by('id'): 
      print(u'{}\t{}\t{}'.format(cat.id, cat.short_name, cat.name))
  # 17257           Nutritional Supplements
  # 19159           Outdoor & Garden
  # 19457           Health & Beauty
  # 21244           Food
  # 21924           Household & Family

So we're not setting short-names for any of the root cateories.  We
could change to use “Nutritional Supplements” as the short-name (so
the URL wouldn't change) and “Natural & Organic Homeopathy -
Nutritional Supplements - Herbal Remedies” as the name.  Then you
could set the header title dynamically, but we'd get a different value
in the sidebar [2] and such (unless we switched the sidebar to use
short-name).  The hard-coded titles are a bit long for the sidebar, so
if we want a very short name (for the URL and such), a medium name
(for the sidebar and such), and a long name (for SEO), then an
seo-title (or seo-name?  long-name?) property makes sense.

Also, I think we may want to be using short-name in the breadcrumbs
[3].  That would give breadcrumbs like:

  Vitamins and Minerals → Vitamins → A

vs. the current [4]:

  Vitamins and Minerals → Vitamins → Vitamin A

The website doesn't seem to be using short-name anywhere (although it
is using slug which can consume the short-name data, since
azurestandard/website@1e7c39cf2).

[1]: https://github.com/azurestandard/website/blob/v1.7.8/src/app.shop/shop_listing.index.controller.js#L506-L525
[2]: https://github.com/azurestandard/website/blob/v1.7.8/src/app.shop/shop_listing.index.html#L84-L87
[3]: https://github.com/azurestandard/website/blob/v1.7.8/src/app.shop/shop_listing.index.html#L22-L31
[4]: https://www.azurestandard.com/shop/category/nutritional-supplements/vitamins-minerals/vitamins/a/17704

**Comment by davidmcatee-azure** [comment]
> if we want a very short name (for the URL and such), a medium name
> (for the sidebar and such), and a long name (for SEO), then an
> seo-title (or seo-name?  long-name?) property makes sense.

Yes, I think this is what we need. I like `seo-title` because I think we should only use this specifically for that purpose.

> I think we may want to be using short-name in the breadcrumbs

I think I agree with this. The breadcrumbs can get pretty long and verbose.
