### ISSUE TITLE
Product Data Check API Endpoints

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/api-spec#259]
# Product Data Check Types

### GET Request

Get a list of all the product data check types.

**Example:**

https://api.azurestandard.com/product-data-check-type

**Response:**

```json
[
  {
    "id": 1,
    "active": true,
    "name": "Incorrect Image"
  }
  {
    "id": 2,
    "active": true,
    "name": "Incorrect ingredients"
  }
  {
    "id": 3,
    "active": true,
    "name": "Incorrect physical characteristics (size, weight)"
  }
]
```

# Product Data Checks

Paging would be handled like all our other endpoints.

### GET Request

Get a list of all the product data checks.

**Example:**

https://api.azurestandard.com/product-data-check

**Response:**

```json
[
  {
    "id": 1,
    "createdAt": "2018-10-16T08:53:47.213810",
    "createdBy": {
      "name": "John Doe"
    },
    "dataCheckTypeId": 1,
    "productId": 1234,
    "completedAt": "2018-10-16T08:53:47.213810",
    "completedBy": {
      "name": "Greg Smith"
    },
    "note": "My note here"
  },
  {
    "id": 2,
    "createdAt": "2018-10-16T08:53:47.213810",
    "createdBy": {
      "name": "John Doe"
    },
    "dataCheckTypeId": 2,
    "productId": 1234,
    "completedAt": null,
    "completedBy": null,
    "note": "My note here"
  },
  {
    "id": 3,
    "createdAt": "2018-10-16T08:53:47.213810",
    "createdBy": {
      "name": "John Doe"
    },
    "dataCheckTypeId": 2,
    "productId": 4321,
    "completedAt": "2018-10-16T08:53:47.213810",
    "completedBy": {
      "name": "Greg Smith"
    },
    "note": "My note here"
  }
]
```

### GET Request

Get a list of all the product data checks.

**Example:**

https://api.azurestandard.com/product-data-check/3

**Response:**

```json
[
  {
    "id": 3,
    "createdAt": "2018-10-16T08:53:47.213810",
    "createdBy": {
      "name": "John Doe"
    },
    "dataCheckTypeId": 2,
    "productId": 4321,
    "completedAt": "2018-10-16T08:53:47.213810",
    "completedBy": {
      "name": "Greg Smith"
    },
    "note": "My note here"
  }
]
```

### POST Request (New Entry)

Create a new product data check entry.

**Example:**

https://api.azurestandard.com/product-data-check

```json
[
  {
    "dataCheckTypeId": 2,
    "productId": 4321,
  }
]
```

**Response:**

```json
[
  {
    "id": 2,
    "createdAt": "2018-10-16T08:53:47.213810",
    "createdBy": {
      "name": "John Doe"
    },
    "dataCheckTypeId": 2,
    "productId": 4321,
    "completedAt": null,
    "completedBy": null,
    "note": ""
  }
]
```

### POST Request (Mark Completed)

Mark a data check as completed.

**Example:**

https://api.azurestandard.com/product-data-check/2/actions/mark-completed

**Response:**

```json
[
  {
    "id": 2,
    "createdAt": "2018-10-16T08:53:47.213810",
    "createdBy": {
      "name": "John Doe"
    },
    "dataCheckTypeId": 2,
    "productId": 4321,
    "completedAt": "2018-10-16T08:53:47.213810",
    "completedBy": {
      "name": "Greg Smith"
    },
    "note": "My note here"
  }
]
```

**Comment by caseybessette** [comment]
> # Product Data Check Types
> We only have three types so for now we will not bother with an API around
> types and just hard code these ID's on the frontend.

I would suggest just doing the API for it, it's easy.

> **NOTE:** Once we do decide to support this in the API we only want a `GET` and
> `POST`. We do not want to support updating (`PUT`) or deleting (`DELETE`) these on the
> frontend due to the historical ramifications.

Regarding `PUT`, we'll need that so they can be marked inactive.  Also, I don't see anything wrong with repairing some wording in the name.   A note on the front-end could say, "Don't alter the essence of the data check, only fix spelling error, etc."

We want to save a history?  `DELETE` can be allowed for types with no history.

> # Product Data Checks
> Paging would be handled like all our other endpoints.
> 
> ## Plural
> ### GET Request
> Get a list of all the product data checks.
> 
> **Example:**
> 
> https://api.azurestandard.com/product-data-checks

I think we should break our current pattern and use singular for all new endpoints.  It's really bad practice to have one endpoint name for singular and another for plural.  It should just be

- `https://api.azurestandard.com/product-data-check` (plural)
- `https://api.azurestandard.com/product-data-check/1` (singular)

The plural endpoint is probably going to need to be able to filter on `productId`.

> **Response:**
> 
> ```json
> [
>   {
>     "id": 1,
>     "created-at": "2018-10-16T08:53:47.213810",
>     "created-by": {
>       "id": 1,
>       "name": "John Doe"
>     },
>     "data-check-type": 1,
>     "product": 1234,
>     "completed-at": "2018-10-16T08:53:47.213810",
>     "completed-by": {
>       "id": 1,
>       "name": "Greg Smith"
>     },
>     "note": "My note here"
>   },
> ```

We are not using dashes for any new JSON properties.  They should all be camelCase.  Also, whenever we provide an ID, we need to specify that it's an ID in the name.  E.g., `data-check-type` should be `dataCheckTypeId` and `product` should be `productId`.

I would suggest this for the createdBy and completedBy properties:

```json
     "completedBy": {
       "name": "Greg Smith"
     },
```

Just cut the ID out.  The problem is that the database stores the user ID.  If the front-end isn't going to use the ID, let's not waste time getting it--the front-end is probably just going to display the name.

> ```json
>   {
>     "id": 2,
>     "created-at": "2018-10-16T08:53:47.213810",
>     "created-by": {
>       "id": 1,
>       "name": "John Doe"
>     },
>     "data-check-type": 2,
>     "product": 1234,
>     "completed-at": "",  // Does a blank string work if there is no data?
>     "completed-by": "",  // Does a blank string work if there is no data?
> ```

Just return `None` here in Python (which will return `null` in JSON) or don't return the property at all.

> ```json
>     "note": "My note here"
>   },
>   {
>     "id": 3,
>     "created-at": "2018-10-16T08:53:47.213810",
>     "created-by": {
>       "id": 1,
>       "name": "John Doe"
>     },
>     "data-check-type": 2,
>     "product": 4321,
>     "completed-at": "2018-10-16T08:53:47.213810",
>     "completed-by": {
>       "id": 1,
>       "name": "Greg Smith"
>     },
>     "note": "My note here"
>   }
> ]
> ```
> 
> ## Singular
> ### PUT Request
> Update a product data check entry.
> 
> **Example:**
> 
> https://api.azurestandard.com/product-data-check/3
> 
> ```json
> [
>   {
>     "data-check-type": 2,
>     "product": 4321,
>     "completed-at": "2018-10-16T08:53:47.213810",
>     "completed-by": 1, // Would this be available to the frontend?
>     "note": "My note here"
>   }
> ]
> ```

Completed values should not be allowed to be set.  Instead, add another endpoint:

- `POST https://api.azurestandard.com/product-data-check/3/actions/mark-completed`

The backend will know what to do.

> ### DELETE Request
> Delete a product data check entry.
> 
> **Example:**
> 
> https://api.azurestandard.com/product-data-check/3

Under which case will these be deleted vs getting marked as completed?
