### ISSUE TITLE
Handle Truck Number in API

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/api-spec#289]
# Background
Trips can have multiple trucks (PickSets).  At this point the API has no way of knowing what truck is delivering for a stop.  The DriverApp could use this info so that a driver is only working with their stops and not a list of stops that could be delivered on other trucks.  In addition the logistics application could also benefit from the ability to group by truck as well

**Note:** While we are not adding driver info specific to each truck that is something we want to consider for the future.  Right now the driver info is stored at the route level.  It should really be at the pickset level.

### Trip Endpoint

- On the trip endpoint add a `truckIds` property as an array.  The array would be PickSet id's that are available in the given trip. 
- This array would be undefined if the trip is not yet verified as trucks are not setup until verification time.

### Stop Endpoint

- Allow the stop endpoint to be filtered by `truckId`.
- On the stop endpoint add a `truckId` and `truckNumber` property as integers.
- These properties would be undefined if the trip is not yet verified.

### Trip Endpoint

- On the trip endpoint add a `truckIds` property as an array.  The array would be PickSet id's that are available in the given trip. 
- This array would be undefined if the trip is not yet verified as trucks are not setup until verification time.

### Stop Endpoint

- Allow the stop endpoint to be filtered by `truckId`.
- On the stop endpoint add a `truck` object.  Within that object have a property for `id` and `number` as integers.  Then as we add `driverName` and `driverPhone` in the future it would also appear in this object.
- The `truck` object would be undefined if the trip is not yet verified.

**Comment by davidmcatee-azure** [comment]
If we were to make it similar to how the rest of the API is structured, trucks (PickSets) would have their own endpoint.

While the name "truck" is more user-friendly, when you think of it as an entity, it sounds like it would represent a specific physical truck.

So maybe something like "truck-load" would be more accurate. But I think we could actually keep the name "pick-set" to avoid confusion, since this is something only we would use.

I'm thinking their would be an API endpoint for pick-sets (with singular and plural). The object returned from it would have `id` and `truckNumber` properties (and could include more such as total weight and volume for example).  In the future we could add the `driverId` (not `driverName` and `driverPhone`, because the driver would be retrieved from the `person` endpoint using the `driverId`, or it could be inlined onto the `pick-set` object using `?inline=driver` as we have done elsewhere).

So in summary:

### Trip Endpoint

- No changes required. PickSets for a given trip could be retrieved using `/pick-sets?tripId={tripId}`.

### Stop Endpoint

- Allow the stop endpoint to be filtered by `pickSetId` (this may in fact not be needed, as the frontends are likely to need all stops on a trip anyway, but would simply group them by pick set--so wait and see if frontend requests this).
- On the stop endpoint add a `pickSetId` (possibly add `inline=pickSet` option, but wait and see if frontend requests this). This would be undefined if the trip is not yet verified.

### PickSet Endpoint (/pick-set/{pickSetId} and /pick-sets)

- Allow plural to be filtered by `tripId`
- Return PickSet objects with `id` and `truckNumber` (and possibly other properties if we want to, such as weight and volume).

In this way, the frontend could retrieve the pickSets for a trip using `/pick-sets?tripId={tripId}` and map them to stops by `pickSetId` instead of getting repeated pickSet info on each stop.

**Comment by tompetersjr** [comment]
> If we were to make it similar to how the rest of the API is structured, trucks (PickSets) would have their own endpoint.

I like that approach.  Will this approach work for you @igregson?

**Comment by igregson** [comment]
> [...] instead of getting repeated pickSet info on each stop.

This seems like a good reason to go with a new endpoint (to prevent data duplication).

As for what to name it, I'd prefer something like `truck-load` or `trip-truck` to `pick-set`. To me, this isn't so much about user friendliness as it is about descriptiveness and accuracy (i.e. accurately and intuitively conveying its meaning). It seems this endpoint will be more logistics-centric than warehouse-centric (since it will have properties related to the driver), so why not name it accordingly? All the while, if it's actually _less_ confusing to have a closer 1-to-1 mapping of the relevant backend terminology, then I suppose that's a good reason to use `pick-set`.

### Trip endpoint

An inline option for the trip's `tripTrucks` (or whatever we call it) would be super useful (it would return an array of the `tripTrucks` if the trip is verified, otherwise undefined).

### Stop Endpoint

The proposed changes look good to me.

### New Endpoint

The proposed structure looks good to me.

**Comment by igregson** [comment]
I realized that any time the frontend would need the truck/pick-set data it would also need the trip data, so I don't see a need for a new endpoint; we could simply include a trip's trucks/pick-sets as an array in the trip response and the truck/pick-set id on the stop response (to map stop to their truck/pick-set).

The tradeoff here that I see is not being able to query the truck/pickset data directly, but I can't think of any case where that would be desirable. The benefits here are not having to add any HTTP requests and reduced complexity. Any specific reason we don't want to go with this approach?

**Comment by davidmcatee-azure** [comment]
We discussed and decided it would be better to go with the name `truckload` since the API naming overall is more frontend-focused.

### Trip endpoint

Include `truckloadIds` array if trip is verified. Provide an `inline=truckloads` option to return an array of `truckloads` as well. We may want to restrict access to these via the ACL so that they are not visible to customers.

### Stop Endpoint

On the stop endpoint add a `truckloadId` (corresponding to the PickSet id). This would be undefined if the trip is not yet verified.

### New Endpoint

We do not need to implement it yet because the frontend will use the trip inline option. But if/when we do need it, it would be `/truckload/{truckloadId}` and `/truckloads` with `?tripId` filter.
