### ISSUE TITLE
Create endpoint to validate email is unique

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/api-spec#60]
Spec out an endpoint to verify uniqueness of an email address.  This is to be used for website issue [#115](https://github.com/azurestandard/website/issues/115) to verify the email address being used is unique.

**Comment by wking** [comment]
On Tue, Jan 19, 2016 at 08:56:07AM -0800, Tom Peters wrote:
> Spec out an endpoint to verify uniqueness of an email address.  This
> is to be used for website issue azurestandard/website#115 to verify
> the email address being used is unique.

Thinking about this some more, I'm pretty sure we don't want to
visibly refuse duplicate-email attempts in the API.  That can leak
“does this address belong to an Azure customer”, since an attacker
with an email address could hit the registration endpoint with the
email in question, and look for an “already in use” error message.
Instead, I think we want to follow the approach taken by the in-flight
password-reset API (fb60b189, public.json: Add 'POST /password/reset'
and 'POST /password/confirm', 2015-11-13, #52), which as:

  "description": "Password-reset email sent (if the registration email
    corresponded to an existing person.  Otherwise, you'll still get a
    204 to avoid leaking information about member email addresses)"

So I'd suggest /registration/register always 200, returning a dummy
(non-functional) resend token if the user enters an already-in-use
email address.  We'd also want updates to /registration/resend to
pretend those invalid tokens lead to resends.  That handles the “don't
leak member information” angle, but doesn't get into customer
usability.

If an existing user accidentally tries to register with an in-use
email, I'd suggest sending them an email.  Content like:

  You just tried to register for an Azure account with this email
  address, but you're already a member (customer number ###)!  If
  you've forgotten your password, go to $LINK to reset it.  If you
  remember your password, you don't have to do anything.

I'm not sure how we should handle inactive customers.  Do they get
activated again?  Do we ever inactivate customers where we'd want to
block such reactivation?

**Comment by tompetersjr** [comment]
I like the suggestion and am good going this route.  I'll add the inactive part of the question to a software call agenda.

**Comment by tompetersjr** [comment]
Creating a more direct issue on the approved solution to this issue from our software meeting on 2-1-2016.
