### ISSUE TITLE
Spec out As Low As Pricing for Packaged-Products

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/api-spec#90]
The website will need to display the lowest price as described in website issue [#225](https://github.com/azurestandard/website/issues/225).  In order to do that we should include this in the packaged-product so that it does not need to be computed client side.

**Comment by wking** [comment]
There was some previous work in this direction [here][1] (part of an earlier version of azurestandard/beehive#1362).  Although instead of putting an “as low as” field on the product, it may be easier to stay consistent between different customer price levels by putting “price per smallest unit” and “smallest unit” fields in [`_price`][2], and let the client iterate through their available packaging to figure out which is actually the smallest.

[1]: https://github.com/azurestandard/beehive/blame/62fb5a081c62bdbe4379e82d43b7a6c7a637d57f/apps/warehouse_pieces/models.py#L340
[2]: https://github.com/azurestandard/api-spec/blob/4ea9517b7eff8a0e5714fdc6f29d75a882853592/public.json#L4603-L4624
