### ISSUE TITLE
Filtering packaged-product-tags by category

### ISSUE THREAD

**Issue by davidmcatee-azure** [azurestandard/api-spec#97]
Is this officially supported?
http://demo-beehive.azurestandardtech.com:8000/api/packaged-product-tags?internal=false&category=characteristic

I didn't see it in the spec but it works and I want to use it for Shopping Filters.

**Comment by wking** [comment]
On Fri, Apr 15, 2016 at 06:54:14PM -0700, David McAtee wrote:
> Is this officially supported?
> http://demo-beehive.azurestandardtech.com:8000/api/packaged-product-tags?internal=false&category=characteristic
> 
> I didn't see it in the spec but it works and I want to use it for
> Shopping Filters.

Looks like it's in master since azurestandard/beehive@c6c12204 (Add
category and filtering to packaged product tags API, 2015-12-04,
azurestandard/beehive#1383), and #21 just missed documenting the
‘category’ filter parameter.  Feel free to file a PR documenting it.
